### PR TITLE
feat: Auto-merge Dependabot pull requests

### PR DESCRIPTION
**Pull request by l0b0**

### CODE REVIEW

**Review by blacha — CHANGES_REQUESTED** [review]
I do not think we should auto merge dependencies.

**Comment by blacha** [comment]
> This code isn't packaged or deployed anywhere directly, so as far as I can tell there's basically zero risk.

This is a template for code that is automatically packaged and deployed so this is a huge risk.

**Comment by l0b0** [comment]
> > This code isn't packaged or deployed anywhere directly, so as far as I can tell there's basically zero risk.
> 
> This is a template for code that is automatically packaged and deployed so this is a huge risk.

Good point. I've added a note in the readme, instructing the user to review the configuration. They might have even stricter safety requirements than both of our groups, after all.

**Comment by l0b0** [comment]
@blacha What's your position on this after the documentation changes?

**Comment by l0b0** [comment]
Ping? This just means the "automerge :rocket:" label gets added automatically; each PR still has to pass all the tests.

**Comment by blacha** [comment]
Automerging dependencies upgrades blindly is very dangerous and is not something we should be advocating for ever, let alone for new comers who are just learning python.

We are also slowly moving off kodiak towards github merge queues which does not have this "feature" anyway.

**Pull request closed without merging**
