### PR TITLE
fix: allow TODO in comments

### PR DESCRIPTION
**Pull request by blacha**
This allows TODO: to be present in comments, it is useful to explain to future developers areas of concern inside of a codebase.

### CODE REVIEW

**Comment by blacha** [comment]
@dwsilk 80 character limit on git commit body messages! that is tiny, is this something we could configure?

**Comment by blacha** [comment]
Looking at  https://www.conventionalcommits.org/en/v1.0.0/

> A longer commit body MAY be provided after the short description, providing additional contextual information about the code changes. The body MUST begin one blank line after the description.
> A commit body is free-form and MAY consist of any number of newline separated paragraphs.

which implies this 80 character limit is not really part of the spec

**Comment by dwsilk** [comment]
It isn't a character limit, it's a line length limit - it wants you to wrap text at character 80. It's not part of conventional commits, it's part of the standard rules in `gitlint`.

We could configure it to be longer by default in `.gitlint`, and then the configuration is also more visible, e.g.
```
[body-max-line-length]
line-length=120
```

This is the link @palmerj provided on the original pull request on commit linting, it recommends wrapping text at 72 chars: https://chris.beams.io/posts/git-commit/#wrap-72

On this particular issue, I feel like there are two different groups of users and no ideal middle ground that suits both.

**Comment by palmerj** [comment]
> This is the link @palmerj provided on the original pull request on commit linting, it recommends wrapping text at 72 chars: https://chris.beams.io/posts/git-commit/#wrap-72

I think it would be good to have summary comment at 50 characters. Also having the body context wrapped (i.e newline) at 72 characters is the nicest for me when viewing `git log` messages on the terminal

**Comment by dwsilk** [comment]
Created an issue regarding this here: https://github.com/linz/template-python-hello-world/issues/12

The discussion will be lost on this unrelated PR.

**Comment by dwsilk** [comment]
@blacha could you change your commit body to:

```TODO is useful to explain areas of concern to future developers.```

to get this through before we resolve the commit message body length configuration.

**Pull request merged**
